=== GabrielOlivaw/CivVQuickRef/xml-resources/jaxb/civvquickref/CivVQuickRef.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="civilizationv" type="CivilizationVGame" />
    
    <!-- Every Civilization V game data includes the mod which it's based on and 
    the list of civilizations it contains. -->
    
    <xs:complexType name="CivilizationVGame">
        <xs:sequence>
            <xs:element name="mod" type="xs:string" />
            <xs:element name="civlist" type="CivilizationList" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- The list of civilizations contained in the game data. -->
    
    <xs:complexType name="CivilizationList">
        <xs:sequence>
            
            <!-- Each civilization is composed by its name, the name of the 
            leader, the image file name, the unique skill of that civilization 
            and the two unique units it has. -->
            <xs:element name="civ" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="civname" type="xs:string" />
                        
                        <xs:element name="civleader" type="xs:string" />
                        
                        <xs:element name="civimg" type="xs:string" />
                        
                        <xs:element name="civskill" type="xs:string" />
                        
                        <!-- Each one of the two units of a civilization have a 
                        name, a type (unit, building or improvement) and the 
                        common unit it replaces. -->
                        
                        <xs:element name="civunits">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="unit" minOccurs="2" maxOccurs="2">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="unitname" type="xs:string" />
                                                
                                                <xs:element name="unittype">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="Unit" />
                                                            <xs:enumeration value="Building" />
                                                            <xs:enumeration value="Improvement" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                                
                                                <xs:element name="unitreplaces" type="xs:string" />
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== GabrielOlivaw/CivVQuickRef/civvquickref/CivVQuickRef.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<civilizationv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="CivVQuickRef.xsd">
    
    <mod>Core - Brave New World</mod>
    
    <civlist>
        <civ>
            <civname>American</civname>
            <civleader>Washington</civleader>
            <civimg>american</civimg>
            <civskill>Manifest Destiny - All land military units have +1 Sight. 50% discount when purchasing tiles.</civskill>
            
            <civunits>
                <unit>
                    <unitname>B17</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Bomber</unitreplaces>
                </unit>
                <unit>
                    <unitname>Minuteman</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Musketman</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Arabian</civname>
            <civleader>Harun al-Rashid</civleader>
            <civimg>arabian</civimg>
            <civskill>Ships of the Desert - Caravans gain 50% extended range. Your trade routes spread the home city's religion twice as effectively. Oil resources are doubled.</civskill>
            
            <civunits>
                <unit>
                    <unitname>Camel Archer</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Knight</unitreplaces>
                </unit>
                <unit>
                    <unitname>Bazaar</unitname>
                    <unittype>Building</unittype>
                    <unitreplaces>Market</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Assyrian</civname>
            <civleader>Ashurbanipal</civleader>
            <civimg>assyrian</civimg>
            <civskill>Treasures of Nineveh - When a city is conquered, gain a free Technology already discovered by its owner. Gaining a city through a trade deal does not count, and it can only happen once per enemy city.</civskill>
            
            <civunits>
                <unit>
                    <unitname>Siege tower</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Catapult</unitreplaces>
                </unit>
                <unit>
                    <unitname>Royal Library</unitname>
                    <unittype>Building</unittype>
                    <unitreplaces>Library</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Austrian</civname>
            <civleader>Maria Theresa</civleader>
            <civimg>austrian</civimg>
            <civskill>Diplomatic Marriage - Can spend Gold to annex or puppet a City-State that has been your ally for 5 turns.</civskill>
            
            <civunits>
                <unit>
                    <unitname>Hussar</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Cavalry</unitreplaces>
                </unit>
                <unit>
                    <unitname>Coffee House</unitname>
                    <unittype>Building</unittype>
                    <unitreplaces>Windmill</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Aztec</civname>
            <civleader>Montezuma</civleader>
            <civimg>aztec</civimg>
            <civskill>Sacrificial Captives - Gains Culture for the empire from each enemy unit killed.</civskill>
            
            <civunits>
                <unit>
                    <unitname>Jaguar</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Warrior</unitreplaces>
                </unit>
                <unit>
                    <unitname>Floating Gardens</unitname>
                    <unittype>Building</unittype>
                    <unitreplaces>Water Mill</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Babylonian</civname>
            <civleader>Nebuchadnezzar II</civleader>
            <civimg>babylonian</civimg>
            <civskill>Ingenuity - Receive free Great Scientist when you discover Writing. Earn Great Scientists 50% faster.</civskill>
            
            <civunits>
                <unit>
                    <unitname>Bowman</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Archer</unitreplaces>
                </unit>
                <unit>
                    <unitname>Walls of Babylon</unitname>
                    <unittype>Building</unittype>
                    <unitreplaces>Walls</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Brazilian</civname>
            <civleader>Pedro II</civleader>
            <civimg>brazilian</civimg>
            <civskill>Carnival - Tourism output is +100% during their Golden Ages. Earn Great Artists, Musicians, and Writers 50% faster during their Golden Ages.</civskill>
            
            <civunits>
                <unit>
                    <unitname>Pracinha</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Infantry</unitreplaces>
                </unit>
                <unit>
                    <unitname>Brazilwood Camp</unitname>
                    <unittype>Improvement</unittype>
                    <unitreplaces></unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Byzantine</civname>
            <civleader>Theodora</civleader>
            <civimg>byzantine</civimg>
            <civskill>Patriarchate of Constantinople - Choose one more Belief than normal when you found a Religion.</civskill>
            
            <civunits>
                <unit>
                    <unitname>Cataphract</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Horseman</unitreplaces>
                </unit>
                <unit>
                    <unitname>Dromon</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Trireme</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Carthaginian</civname>
            <civleader>Dido</civleader>
            <civimg>carthaginian</civimg>
            <civskill>Phoenician Heritage - All coastal Cities get a free Harbor. Units may cross mountains after the first Great General is earned, taking 50 HP damage if they end a turn on a mountain.</civskill>
            
            <civunits>
                <unit>
                    <unitname>African Forest Elephant</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Horseman</unitreplaces>
                </unit>
                <unit>
                    <unitname>Quinquereme</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Trireme</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Celtic</civname>
            <civleader>Boudicca</civleader>
            <civimg>celtic</civimg>
            <civskill>Druidic Lore - +1 Faith per city with an adjacent unimproved Forest. Bonus increases to +2 Faith in Cities with 3 or more adjacent unimproved Forest tiles.</civskill>
            
            <civunits>
                <unit>
                    <unitname>Pictish Warrior</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Spearman</unitreplaces>
                </unit>
                <unit>
                    <unitname>Ceilidh Hall</unitname>
                    <unittype>Building</unittype>
                    <unitreplaces>Opera House</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Chinese</civname>
            <civleader>Wu Zetian</civleader>
            <civimg>chinese</civimg>
            <civskill>Art of War - The Great General combat bonus is increased by 15%, and their spawn rate is increased by 50%.</civskill>
            
            <civunits>
                <unit>
                    <unitname>Chu-Ko-Nu</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Crossbowman</unitreplaces>
                </unit>
                <unit>
                    <unitname>Paper Maker</unitname>
                    <unittype>Building</unittype>
                    <unitreplaces>Library</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Danish</civname>
            <civleader>Harald Bluetooth</civleader>
            <civimg>danish</civimg>
            <civskill>Viking Fury - Embarked units have +1 Movement and pay just 1 movement point to move from sea to land. Melee units pay no movement point cost to pillage.</civskill>
            
            <civunits>
                <unit>
                    <unitname>Berserker</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Longswordsman</unitreplaces>
                </unit>
                <unit>
                    <unitname>Norwegian Ski Infantry</unitname>
                    <unittype>Unit</unittype>
                    <unitreplaces>Rifleman</unitreplaces>
                </unit>
            </civunits>
        </civ>
        <civ>
            <civname>Dutch</civname>
            <civleader>William</civleader>
            <civimg>dutch</civimg>
